# Change these first
owner: K2Lin-Daniel # Your GitHub organization or username, where this repository lives
repo: K2Lin_Status # The name of this repository

sites:
  - name: K2Lin Tech Tips
    url: https://k2lin.com
  - name: K2Lin Cloud Music
    url: https://music.k2lin.com
  - name: K2Lin Chat
    url: https://chat.k2lin.com
  - name: K2Lin Auth
    url: https://auth.k2lin.com
  - name: OurCraft Network
    check: "tcp-ping"
    url: cloud.k2lin.studio
    port: 26775

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/15 * * * *"

i18n:
  footer: K2Lin Status Monitor [open source on GitHub]($REPO).

status-website:
  theme: night
  themeUrl: https://raw.githubusercontent.com/K2Lin-Daniel/K2Lin_Status/master/assets/azure.css
  customHeadHtml: "<link rel='preconnect' href='https://fonts.googleapis.com'><link rel='preconnect' href='https://fonts.gstatic.com' crossorigin><link href='https://fonts.googleapis.com/css2?family=Comfortaa:wght@300&display=swap' rel='stylesheet'>"
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.k2lin.com
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/K2Lin-Daniel/K2Lin_Status/master/assets/KTT-Icon.png
  favicon: https://raw.githubusercontent.com/K2Lin-Daniel/K2Lin_Status/master/assets/KTT_Favicon.png

  name: K2Lin Status
  introTitle: "**K2Lin Status** 🚀"
  introMessage: Status watcher! For K2Lin Tech Tips projects, and more! 🕰️ [K2Lin.com](https://k2lin.com/).
  navbar:
    - title: Status
      href: /
    - title: Main
      href: https://k2lin.com/
    - title: Music
      href: https://music.k2lin.com/
    - title: Chat
      href: https://chat.k2lin.com/
    - title: OurCraft
      href: https://ourcraft.cyou/

