# Change these first
owner: K2Lin-Daniel # Your GitHub organization or username, where this repository lives
repo: K2Lin_Status # The name of this repository

sites:
  - name: K2Lin Tech Tips
    url: https://k2lin.com
  - name: K2Lin Cloud Music
    url: https://music.k2lin.com
  - name: K2Lin Chat
    url: https://chat.k2lin.com
  - name: K2Lin Auth
    url: https://auth.k2lin.com
  - name: Wikipedia
    url: https://en.wikipedia.org

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.k2lin.com
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: K2Lin Status
  introTitle: "**K2Lin Status** 🚀"
  introMessage: Status watcher! For K2Lin Tech Tips projects, and more! 🕰️ [K2Lin Tech Tips](https://k2lin.com/).
  navbar:
    - title: Status
      href: /
    - title: Main
      href: https://k2lin.com/
    - title: Music
      href: https://music.k2lin.com/
    - title: Chat
      href: https://chat.k2lin.com/

