# Change these first
owner: K2Lin-Daniel # Your GitHub organization or username, where this repository lives
repo: K2Lin_Status # The name of this repository

sites:
  - name: Main Site
    url: https://k2lin.com
    icon: https://raw.githubusercontent.com/K2Lin-Daniel/K2Lin_Status/master/assets/Cloud-Icon.png
    maxResponseTime: 4000
  - name: Cloud Music
    url: https://music.k2lin.com
    icon: https://raw.githubusercontent.com/K2Lin-Daniel/K2Lin_Status/master/assets/Cloud-Icon.png
  - name: Chat
    url: https://chat.k2lin.com
    icon: https://raw.githubusercontent.com/K2Lin-Daniel/K2Lin_Status/master/assets/Cloud-Icon.png
    maxResponseTime: 4000
  - name: Auth
    url: https://auth.k2lin.com
    icon: https://raw.githubusercontent.com/K2Lin-Daniel/K2Lin_Status/master/assets/Cloud-Icon.png
    maxResponseTime: 4000
  - name: OurCraft Network
    check: "tcp-ping"
    url: mc.ocn.moe
    icon: https://raw.githubusercontent.com/K2Lin-Daniel/K2Lin_Status/master/assets/Cloud-Icon.png
    maxResponseTime: 2250
    port: 26775

workflowSchedule:
  graphs: "10 */2 * * *"
  responseTime: "15 * * * *"
  staticSite: "20 */6 * * *"
  summary: "35 */6 * * *"
  updateTemplate: "0 1 * * *"
  updates: "0 3 * * *"
  uptime: "*/10 * * * *"

i18n:
  footer: K2Lin Status Monitor - K2Lin Teams 2023

status-website:
  theme: night
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.k2lin.com
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/K2Lin-Daniel/K2Lin_Status/master/assets/KTT-Icon.png
  favicon: https://raw.githubusercontent.com/K2Lin-Daniel/K2Lin_Status/master/assets/KTT_Favicon.png

  metaTags:
  - name: "description"
    content: "Service Status watcher! For K2Lin Tech Tips projects, and more!🚀"
  - name: "color-scheme"
    content: "dark light"

  name: K2Lin Status
  introTitle: "**K2Lin Status Monitor** 🚀"
  introMessage: ☘️Service Status watcher! For K2Lin Tech Tips projects, and more!  🔁[K2Lin.com](https://k2lin.com/).
  navbar:
    - title: Status
      href: /
    - title: Main
      href: https://k2lin.com/
    - title: Music
      href: https://music.k2lin.com/
    - title: Chat
      href: https://chat.k2lin.com/
    - title: OurCraft
      href: https://ourcraft.cyou/
  css: "body { font-family: 'Comfortaa', Droid Sans, Helvetica, sans-serif }"
